Repository CHOMPStation2/CHOMPStation2, pull requests merged in 2020-01, with the labels that each got.

#100 Re porting unified fabricators
  code/modules/mob/living/silicon/robot/drone/drone_manufacturer_unify.dm
  vorestation.dme
Labels: CHOMPstation content

#81 Removes ball-kicking
  code/modules/mob/living/carbon/human/unarmed_attack.dm
Labels: DO NOT MERGE, bug

#75 Redo of Mapfix Palooza Round One
  code/game/objects/structures/crates_lockers/closets/secure/security_vr.dm
  maps/southern_cross/southern_cross-1.dmm
  maps/southern_cross/southern_cross-3.dmm
  maps/southern_cross/southern_cross-4.dmm
  maps/southern_cross/southern_cross-6.dmm
Labels: DO NOT MERGE, WIP

#115 Adding CHOMP synth_facemask
  code/modules/clothing/masks/tesh_synth_facemask.dm
Labels: CHOMPstation content

#128 Boozeborg [WIP]
  code/global_vr.dm
  code/modules/mob/living/silicon/robot/robot_modules/station.dm
  code/modules/mob/living/silicon/robot/robot_modules/station_vr.dm
  code/modules/mob/living/silicon/robot/subtypes/boozeborg_ch.dm
  icons/mob/dogborg_vr.dmi
  icons/mob/screen1_robot_vr.dmi
  vorestation.dme
Labels: Approved, CHOMPstation content

#142 Groin to mouth marking
  code/modules/mob/new_player/sprite_accessories_ch.dm
  icons/mob/human_races/markings_ch.dmi
Labels: CHOMPstation content

#137 Readding Traits, plus 1 new
  code/modules/mob/living/carbon/human/species/station/station_special_abilities_ch.dm
  code/modules/mob/living/carbon/human/species/station/station_special_abilities_vr.dm
  code/modules/mob/living/carbon/human/species/station/traits_vr/neutral.dm
  code/modules/mob/living/carbon/human/species/station/traits_vr/neutral_ch.dm
  vorestation.dme
Labels: Approved

#154 Correct grammar/formatting for two traits, and rename/adjust traits.
  code/modules/mob/living/carbon/human/species/station/traits_vr/neutral.dm
  code/modules/mob/living/carbon/human/species/station/traits_vr/neutral_ch.dm
Labels: Approved

#155 Add hyenas, and a custom pack_mob ai type for them
  code/modules/ai/aI_holder_subtypes/simple_mob_ai_ch.dm
  code/modules/mob/living/simple_mob/subtypes/animal/hyena/hyena.dm
  icons/mob/animals48x32_ch.dmi
  vorestation.dme
Labels: DO NOT MERGE, WIP

#169 Port Belt Mining over to Southern Cross, and adds Away Mission/Gateway Mission Framework!
  maps/southern_cross/southern_cross-3.dmm
  maps/southern_cross/southern_cross-7.dmm
  maps/southern_cross/southern_cross.dm
  maps/southern_cross/southern_cross_areas.dm
  maps/southern_cross/southern_cross_defines.dm
  maps/southern_cross/southern_cross_presets.dm
  maps/southern_cross/southern_cross_shuttles.dm
  maps/southern_cross/submaps/_southern_cross_submaps.dm
  maps/southern_cross/submaps/asteroid_belt/_templates.dm
  maps/southern_cross/submaps/asteroid_belt/belt_miner_things.dm
  maps/southern_cross/submaps/asteroid_belt/broken_o2_gen.dmm
  maps/southern_cross/submaps/asteroid_belt/corrupt_hound_bay.dmm
  maps/southern_cross/submaps/asteroid_belt/crashed_shuttle.dmm
  maps/southern_cross/submaps/asteroid_belt/frost_spider_nest.dmm
  maps/southern_cross/submaps/asteroid_belt/hard_cave.dmm
  maps/southern_cross/submaps/asteroid_belt/infection_pod.dmm
  maps/southern_cross/submaps/asteroid_belt/inferno.dmm
  maps/southern_cross/submaps/asteroid_belt/large_cave.dmm
  maps/southern_cross/submaps/asteroid_belt/mimicry.dmm
  maps/southern_cross/submaps/asteroid_belt/mysterious_cavern.dmm
  maps/southern_cross/submaps/asteroid_belt/normal_cave.dmm
  maps/southern_cross/submaps/asteroid_belt/pressure_seal.dmm
  maps/southern_cross/submaps/asteroid_belt/space_cave.dmm
  maps/southern_cross/submaps/sc_belt_miner.dmm
Labels: Map Edit

#189 Small changes to POIs and the main outpost based on Virgo Feedback
  maps/southern_cross/submaps/asteroid_belt/broken_o2_gen.dmm
  maps/southern_cross/submaps/asteroid_belt/mysterious_cavern.dmm
  maps/southern_cross/submaps/sc_belt_miner.dmm
Labels: Approved

#185 Add a craftable, two-handed sledgehammer.
  code/game/objects/items/weapons/material/sledgehammer_construction_ch.dm
  code/game/objects/items/weapons/material/twohanded_ch.dm
  code/modules/materials/material_recipes_ch.dm
  icons/mob/items/lefthand_material_ch.dmi
  icons/mob/items/righthand_material_ch.dmi
  icons/obj/hammer_construction_ch.dmi
  icons/obj/hammer_sprites_ch.dmi
  sound/weapons/smash5.ogg
  vorestation.dme
Labels: question
