Repository CHOMPStation2/CHOMPStation2, pull requests merged in 2020-12, with the labels that each got.

#950 ohno
  code/modules/mob/living/simple_mob/subtypes/animal/passive/mouse_mutant_event.dm
  code/modules/mob/living/simple_mob/subtypes/vore/chungus.dm
  vorestation.dme
Labels: CHOMPStation Content

#1016 So this is Christmas...
  code/game/area/Space Station 13 areas_ch.dm
  code/game/machinery/casino_prize_dispenser_ch.dm
  code/game/machinery/event/christmas_ch.dm
  code/game/objects/effects/effect_system_ch.dm
  code/game/objects/items/weapons/gift_wrappaper_ch.dm
  code/game/objects/items/weapons/id cards/CH_ids.dm
  code/modules/shuttles/shuttles_ch.dm
  icons/obj/card.dmi
  icons/obj/card_ch.dmi
  icons/obj/items_ch.dmi
  maps/southern_cross/southern_cross-2.dmm
  maps/southern_cross/southern_cross-3.dmm
  maps/southern_cross/southern_cross-casino.dmm
  maps/southern_cross/southern_cross.dm
  maps/southern_cross/southern_cross_defines.dm
  maps/southern_cross/southern_cross_shuttles_ch.dm
  vorestation.dme
Labels: Approved, Map Edit

#1025 Leopardmander vore mob
  code/modules/mob/living/simple_animal/aliens/synx.dm
  code/modules/mob/living/simple_mob/subtypes/vore/leopardmander_ch.dm
  icons/mob/vore128x64_ch.dmi
  vorestation.dme
Labels: Approved
