Repository CHOMPStation2/CHOMPStation2, pull requests merged in 2021-01, with the labels that each got.

#1144 New Gym on Station!
  maps/southern_cross/southern_cross-1.dmm
  maps/southern_cross/southern_cross-10.dmm
  maps/southern_cross/southern_cross-2.dmm
  maps/southern_cross/southern_cross-3.dmm
  maps/southern_cross/southern_cross-5.dmm
  maps/southern_cross/southern_cross_areas.dm
Labels: Map Edit

#1175 Readds all Sahoc items
  code/game/objects/items/sahoc_ch.dm
  vorestation.dme
Labels: CHOMPStation Content

#1191 The logenning: Privacy begone, and Moderators having context and evidence welcome.
  code/_helpers/logging.dm
  code/_helpers/logging_vr.dm
  code/game/world.dm
  code/modules/admin/admin_tools.dm
Labels: TEST MERGED

#1193 Porting TG's SQL
  code/__defines/subsystems.dm
  code/_helpers/logging.dm
  code/_helpers/logging_vr.dm
  code/_helpers/text.dm
  code/controllers/subsystems/dbcore.dm
  code/controllers/subsystems/persist_vr.dm
  code/defines/procs/statistics.dm
  code/game/world.dm
  code/global.dm
  code/modules/admin/DB ban/functions.dm
  code/modules/admin/IsBanned.dm
  code/modules/admin/admin_ranks.dm
  code/modules/admin/admin_tools.dm
  code/modules/admin/banjob.dm
  code/modules/admin/permissionverbs/permissionedit.dm
  code/modules/admin/verbs/check_customitem_activity.dm
  code/modules/admin/verbs/panicbunker.dm
  code/modules/client/client procs.dm
  code/modules/library/lib_machines.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/mob/new_player/poll.dm
  code/modules/research/message_server.dm
  code/modules/tgs/v5/chat_commands.dm
  vorestation.dme
Labels: TEST MERGED
