Repository CHOMPStation2/CHOMPStation2, pull requests merged in 2022-08, with the labels that each got.

#4653 Brass tools icon fix
  code/game/objects/items/weapons/tools/brass.dm
Labels: Approved

#4226 Vore sprites
  code/__defines/belly_modes_ch.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/human/update_icons_ch.dm
  code/modules/mob/living/silicon/robot/robot_modules/event_vr.dm
  code/modules/mob/living/silicon/robot/robot_modules/station_ch.dm
  code/modules/mob/living/silicon/robot/robot_modules/station_vr.dm
  code/modules/mob/living/silicon/robot/robot_vr.dm
  code/modules/mob/living/silicon/robot/subtypes/boozeborg_ch.dm
  code/modules/mob/living/simple_mob/simple_mob_vr.dm
  code/modules/mob/living/simple_mob/subtypes/vore/bigdragon.dm
  code/modules/mob/living/simple_mob/subtypes/vore/bigdragon_ch.dm
  code/modules/mob/living/simple_mob/subtypes/vore/lamia.dm
  code/modules/vore/eating/belly_obj_ch.dm
  code/modules/vore/eating/belly_obj_vr.dm
  code/modules/vore/eating/living_ch.dm
  code/modules/vore/eating/living_vr.dm
  code/modules/vore/eating/vorepanel_vr.dm
  icons/mob/vore/Bellies.dmi
  icons/mob/vore/Taur_Bellies.dmi
  modular_chomp/code/modules/mob/living/carbon/human/human.dm
  modular_chomp/code/modules/mob/living/carbon/human/human_defines.dm
  modular_chomp/code/modules/mob/living/carbon/human/species/species.dm
  modular_chomp/code/modules/mob/living/carbon/human/species/station/station.dm
  modular_chomp/code/modules/mob/living/carbon/human/species/station/teshari.dm
  modular_chomp/code/modules/mob/living/carbon/human/update_icons.dm
  modular_chomp/code/modules/mob/living/living.dm
  modular_chomp/code/modules/mob/new_player/sprite_accessories_taur.dm
  tgui/packages/tgui/interfaces/VorePanel.js
  tgui/public/tgui.bundle.js
  vorestation.dme
Labels: High Priority, Approved, Icon Edit

#4683 Fixes Demon Tongues
  code/modules/mob/living/simple_mob/subtypes/vore/demon/demon_ch.dm
Labels: Approved

#4676 Improves botany, Puts library in place of gym, adds art gallery, gym in place of public garden
  icons/turf/areas.dmi
  maps/southern_cross/southern_cross-2.dmm
  maps/southern_cross/southern_cross-3.dmm
  maps/southern_cross/southern_cross_areas.dm
Labels: Feature / Enhancement, Needs Discussion, CHOMPStation Content, High Priority, Map Edit, Needs Review

#4728 Gallery Fixes 1.0
  maps/southern_cross/southern_cross-2.dmm
Labels: High Priority

#4713 ReForming Planetside Z-levels
  maps/southern_cross/southern_cross-10.dmm
  maps/southern_cross/southern_cross-12.dmm
  maps/southern_cross/southern_cross-5.dmm
  maps/southern_cross/southern_cross-6.dmm
Labels: Medium Priority, Map Edit, Waiting Test Merge

#4733 Desert Planet Tiles
  modular_chomp/code/game/turfs/simulated/outdoors/desert_planet.dm
  modular_chomp/icons/turf/desert_planet.dmi
  modular_chomp/icons/turf/outdoors_edge.dmi
  vorestation.dme
Labels: WIP

#4614 Vox goodies update!
  code/datums/supplypacks/voidsuits.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/shoes/magboots.dm
  code/modules/clothing/spacesuits/rig/suits/alien.dm
Labels: WIP

#4804 Fixing Wilderness Atmos
  maps/southern_cross/southern_cross-10.dmm
Labels: High Priority, Map Edit
