Repository CHOMPStation2/CHOMPStation2, pull requests merged in 2022-04, with the labels that each got.

#4033 TGMC Ammo HUD Port
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/screen_objects.dm
  code/_onclick/hud/screen_objects_ch.dm
  code/game/objects/items/weapons/grenades/explosive.dm
  code/game/objects/items/weapons/grenades/grenade.dm
  code/game/objects/items/weapons/grenades/smokebomb.dm
  code/modules/power/cell.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/gun_ch.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/cell_loaded_vr/cell_loaded.dm
  code/modules/projectiles/guns/energy/cell_loaded_vr/multi_cannon.dm
  code/modules/projectiles/guns/energy/cell_loaded_vr/multi_cannon_cells.dm
  code/modules/projectiles/guns/energy/cell_loaded_vr/nerd_cells.dm
  code/modules/projectiles/guns/energy/laser_vr.dm
  code/modules/projectiles/guns/projectile.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  code/modules/projectiles/guns/projectile_ch.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/beams_ch.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/projectiles/projectile/bullets_ch.dm
  code/modules/projectiles/projectile/energy.dm
  code/modules/projectiles/projectile/energy_ch.dm
  code/modules/projectiles/projectile/energy_yw.dm
  code/modules/projectiles/projectile/explosive.dm
  code/modules/projectiles/projectile/magnetic.dm
  code/modules/projectiles/projectile/magnetic_ch.dm
  code/modules/projectiles/projectile/special.dm
  icons/mob/screen_ammo.dmi
  vorestation.dme
Labels: TEST MERGED

#4042 [MIRROR] What's that material??? & Techdisk Bluescreen fix
  tgui/packages/tgui/interfaces/ExosuitFabricator.js
  tgui/packages/tgui/interfaces/ResearchConsole.js
  tgui/public/tgui.bundle.js
  vorestation.dme
Labels: TGUI Change

#4124 [MIRROR] Particle Gun Fix
  code/modules/projectiles/guns/energy/particle.dm
  icons/inventory/back/mob.dmi
  icons/inventory/belt/mob.dmi
  icons/mob/items/lefthand_guns.dmi
  icons/mob/items/righthand_guns.dmi
  icons/obj/gun.dmi
  icons/obj/gun_vr.dmi
Labels: [MIRROR] Missing files
