Repository CHOMPStation2/CHOMPStation2, pull requests merged in 2022-10, with the labels that each got.

#4933 Allows for deconstruction and RPED-less upgrading of kitchen appliances. FIXES #4172
  code/modules/food/kitchen/cooking_machines/candy.dm
  code/modules/food/kitchen/cooking_machines/cereal.dm
  code/modules/food/kitchen/cooking_machines/fryer.dm
  code/modules/food/kitchen/cooking_machines/grill.dm
  code/modules/food/kitchen/cooking_machines/oven.dm
  code/modules/food/kitchen/gibber.dm
  code/modules/food/kitchen/icecream.dm
Labels: WIP

#5081 Tie new sprites to Vox suits
  code/modules/clothing/spacesuits/rig/suits/alien.dm
Labels: Approved

#5039 Ports the animal clinic from tgstation as a superimposed pod
  modular_chomp/code/modules/mining/shelter_atoms_ch.dm
  modular_chomp/code/modules/mining/shelters_ch.dm
  modular_chomp/maps/submaps/shelters/AnimalHospital-20x28.dmm
Labels: Low Priority, Approved, Map Edit

#4796 Adds a VR room and a functioning VR map for all your sandbox needs.
  code/game/machinery/virtual_reality/vr_console.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/species/virtual_reality/avatar.dm
  maps/southern_cross/southern_cross-3.dmm
  maps/southern_cross/southern_cross_areas.dm
  maps/southern_cross/submaps/_southern_cross_submaps.dm
  maps/southern_cross/submaps/virtual_reality/constructVR.dm
  maps/southern_cross/submaps/virtual_reality/constructVR.dmm
  modular_chomp/code/modules/mob/mob.dm
Labels: Medium Priority, Approved, Map Edit

#3877 Non crew role added
  code/__defines/misc_ch.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job_controller.dm
  code/game/jobs/jobs.dm
  code/game/objects/effects/landmarks.dm
  code/global_ch.dm
  code/modules/client/preference_setup/occupation/occupation.dm
  code/modules/client/preferences_ch.dm
  code/modules/client/preferences_spawnpoints.dm
  code/modules/mob/new_player/new_player.dm
  maps/southern_cross/southern_cross-5.dmm
  maps/southern_cross/southern_cross_defines.dm
  modular_chomp/code/datums/outfits/jobs/noncrew.dm
  modular_chomp/code/game/jobs/job/department.dm
  modular_chomp/code/game/jobs/job/noncrew.dm
  modular_chomp/code/global.dm
  modular_chomp/code/modules/client/preferences.dm
  modular_chomp/code/modules/client/preferences_spawnpoints.dm
  vorestation.dme
Labels: Needs Discussion, TEST MERGED
