Repository CHOMPStation2/CHOMPStation2, pull requests merged in 2023-03, with the labels that each got.

#5832 Eclipse mobs
  modular_chomp/code/modules/mob/living/simple_mob/subtypes/humanoid/eclipse/eclipse.dm
  modular_chomp/code/modules/mob/living/simple_mob/subtypes/humanoid/eclipse/noms.dm
  modular_chomp/icons/mob/animal_ch.dmi
  vorestation.dme
Labels: Approved

#5812 Item TF spawnpoints
  code/_helpers/global_lists_ch.dm
  code/game/jobs/job_controller.dm
  code/game/objects/items_vr.dm
  code/modules/client/preference_setup/loadout/gear_tweaks_ch.dm
  code/modules/client/preference_setup/loadout/loadout.dm
  code/modules/mob/new_player/new_player.dm
  modular_chomp/code/game/objects/items.dm
  modular_chomp/code/modules/client/preferences_spawnpoints.dm
  vorestation.dme
Labels: Approved

#5798 Ports Lavaland tiles
  modular_chomp/code/game/turfs/simulated/outdoors/lava_land.dm
  modular_chomp/icons/turf/lava_land.dmi
  modular_chomp/icons/turf/lava_land_edge.dmi
  vorestation.dme
Labels: Approved, Icon Edit

#5826 Remove random damage on straight disposal pipes
  code/modules/recycling/disposal.dm
Labels: Approved

#5834 Fixes #5667 VR Crash
  code/modules/vore/mouseray.dm
Labels: Approved

#5839 Buff Promethean limbs
  code/modules/organs/subtypes/slime.dm
Labels: Approved

#5842 Adds Deafened Feedback, enhances looping sounds further
  code/datums/looping_sounds/_looping_sound.dm
  code/datums/looping_sounds/mob_sounds.dm
  code/game/dna/genes/disabilities.dm
  code/game/gamemodes/cult/runes.dm
  code/game/gamemodes/technomancer/spells/audible_deception.dm
  code/game/machinery/jukebox.dm
  code/game/mecha/equipment/weapons/honk.dm
  code/game/objects/explosion.dm
  code/game/objects/items/devices/megaphone.dm
  code/game/objects/items/weapons/grenades/concussion.dm
  code/game/objects/items/weapons/grenades/flashbang.dm
  code/modules/admin/verbs/lightning_strike.dm
  code/modules/mob/living/carbon/alien/alien_damage.dm
  code/modules/mob/living/carbon/alien/life.dm
  code/modules/mob/living/carbon/brain/life.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/nifsoft/software/13_soulcatcher.dm
  code/modules/projectiles/guns/magnetic/magnetic.dm
  code/modules/projectiles/projectile/energy.dm
  code/modules/reagents/reagents/toxins.dm
  code/modules/virus2/effect.dm
  maps/gateway_archive_vr/labyrinth.dm
  modular_chomp/code/modules/mob/living/carbon/human/species/station/protean/protean_rig.dm
  modular_chomp/code/modules/mob/living/living.dm
  modular_chomp/code/modules/reagents/reagents/food_drinks.dm
  modular_chomp/sound/effects/ear_ring/ear_deaf_in.ogg
  modular_chomp/sound/effects/ear_ring/ear_deaf_loop.ogg
  modular_chomp/sound/effects/ear_ring/ear_deaf_out.ogg
  vorestation.dme
Labels: Approved

#5843 Adds Sleep Music to Surgery/Cryo/Sleeper
  code/datums/looping_sounds/mob_sounds.dm
  code/game/machinery/Sleeper.dm
  code/game/machinery/cryo.dm
  code/game/machinery/oxygen_pump.dm
  code/modules/client/preference_setup/global/setting_datums.dm
  code/modules/client/preferences_ch.dm
  modular_chomp/code/modules/mob/living/carbon/carbon.dm
  modular_chomp/sound/misc/cozy.ogg
  vorestation.dme
Labels: Approved

#5781 [MIRROR] Custom Species name in Records
  code/datums/datacore.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/security.dm
  code/game/machinery/computer/skills.dm
  code/game/objects/items/weapons/id cards/station_ids.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/tgui/modules/agentcard.dm
  tgui/packages/tgui/interfaces/IDCard.js
  tgui/public/tgui.bundle.js
Labels: TGUI Change, [MIRROR] Missing files

#5795 [MIRROR] Character Setup Lore Option Tweaks
  code/datums/datacore.dm
  code/datums/uplink/announcements.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/security.dm
  code/game/machinery/computer/skills.dm
  code/game/objects/items/devices/uplink.dm
  code/modules/client/preference_setup/general/05_background.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_factions.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  tgui/packages/tgui/interfaces/Uplink.js
  tgui/public/tgui.bundle.js
Labels: TGUI Change

#5840 Simplemob Injury System
  code/modules/mob/living/simple_mob/combat.dm
  code/modules/mob/living/simple_mob/simple_mob.dm
  code/modules/mob/living/simple_mob/subtypes/humanoid/mercs/mercs.dm
  code/modules/tension/tension.dm
Labels: Needs Discussion
