Repository CHOMPStation2/CHOMPStation2, pull requests merged in 2023-07, with the labels that each got.

#6521 Try fix another runtime
  modular_chomp/maps/submaps/surface_submaps/valley/crashedexplo.dmm
Labels: Approved

#6535 Adds interface options for cell removal and renaming assemblies.
  tgui/packages/tgui_ch/interfaces/ICAssembly.js
Labels: TGUI Change

#6395 Base blep
  maps/southern_cross/southern_cross_defines.dm
  maps/southern_cross/submaps/_southern_cross_submaps.dm
  maps/southern_cross/submaps/gateway/BaseBlep.dm
  maps/southern_cross/submaps/gateway/BaseBlep.dmm
  maps/southern_cross/submaps/gateway/maddnesslab.dm
  maps/southern_cross/submaps/gateway/maddnesslab.dmm
  modular_chomp/code/modules/clothing/gateway/gateway.dm
  modular_chomp/code/modules/mob/living/simple_mob/subtypes/gateway/imperion.dm
  modular_chomp/code/modules/mob/living/simple_mob/subtypes/gateway/vistors.dm
  modular_chomp/code/modules/mob/living/simple_mob/subtypes/gateway/wizards.dm
  modular_chomp/code/modules/mob/living/simple_mob/subtypes/mechanical/hivebot/boss.dm
  modular_chomp/code/modules/mob/living/simple_mob/subtypes/mechanical/hivebot/orginalAlts.dm
  modular_chomp/code/modules/mob/living/simple_mob/subtypes/slimess/feral.dm
  modular_chomp/code/modules/mob/living/simple_mob/subtypes/vore/ashy.dm
  modular_chomp/code/modules/mob/living/simple_mob/subtypes/vore/gateway/candy.dm
  modular_chomp/code/modules/projectiles/guns/staffs.dm
  modular_chomp/code/modules/weapons/melee.dm
  modular_chomp/icons/mob/candy.dmi
  vorestation.dme
Labels: TEST MERGED

#6583 [MIRROR] Adds Custom Subtle verb
  code/_helpers/game.dm
  code/modules/mob/say_ch.dm
  code/modules/mob/say_vr.dm
  code/modules/tables/tables.dm
Labels: Bug, CHOMPStation Content

#6360 [READY TO MERGE] Exploration Carrier Phase One, Phase Weapon Improvements and new Humvee Vehicle
  code/game/sound.dm
  code/modules/projectiles/guns/energy/phase.dm
  code/modules/projectiles/projectile/energy_ch.dm
  code/modules/vehicles/quad.dm
  code/modules/vehicles/rover_vr.dm
  code/modules/vehicles/vehicle.dm
  maps/southern_cross/overmap/sectors.dm
  maps/southern_cross/southern_cross-7.dmm
  maps/southern_cross/southern_cross_areas.dm
  modular_chomp/maps/overmap/aegis_carrier/aegis_icons/greyledge.dmi
  modular_chomp/maps/overmap/aegis_carrier/aegis_icons/ledge.dmi
  modular_chomp/maps/overmap/aegis_carrier/aegis_objs.dm
  modular_chomp/sound/effects/explosions/vehicleexplosion.ogg
  modular_chomp/sound/effects/mech/powerloader_step.ogg
  modular_chomp/sound/effects/mech/powerloader_step2.ogg
  modular_chomp/sound/effects/vehicle/engine_loop.ogg
  modular_chomp/sound/effects/vehicle/engine_loop_finish.ogg
  modular_chomp/sound/effects/vehicle/engine_off.ogg
  modular_chomp/sound/effects/vehicle/ignition_car.ogg
  modular_chomp/sound/weapons/phase_new/phasecannon.ogg
  modular_chomp/sound/weapons/phase_new/phasecarbine.ogg
  modular_chomp/sound/weapons/phase_new/phasepistol.ogg
  modular_chomp/sound/weapons/phase_new/phaserifle.ogg
  vorestation.dme
Labels: WIP, Map Edit, TEST MERGED
