Repository CHOMPStation2/CHOMPStation2, pull requests merged in 2024-04, with the labels that each got.

#7941 Online schizophrenia: The 1 throwforcening
  code/modules/mob/dead/corpse.dm
  code/modules/mob/living/simple_mob/subtypes/vore/leopardmander_ch.dm
  code/modules/recycling/disposal.dm
  code/modules/recycling/sortingmachinery.dm
  code/modules/vore/eating/digest_act_vr.dm
  modular_chomp/code/game/objects/items/devices/vacpack.dm
  modular_chomp/code/modules/mob/living/simple_mob/subtypes/vore/corrupt_hounds.dm
  modular_chomp/code/modules/mob/living/simple_mob/subtypes/vore/swoopie.dm
  modular_chomp/icons/mob/vore_fullscreens/a_tumby.dmi
  modular_chomp/icons/mob/vore_fullscreens/another_tumby.dmi
  modular_chomp/icons/mob/vore_fullscreens/da_tumby.dmi
  modular_chomp/icons/mob/vore_fullscreens/yet_another_tumby.dmi
  vorestation.dme
Labels: Type: Feature / Enhancement, Icon Edit, TEST MERGED, Fix, Quality of Life, TEST MERGE CANDIDATE

#8053 [MIRROR] Gives simple mobs thermals
  code/modules/mob/living/simple_mob/simple_mob.dm
  code/modules/mob/living/simple_mob/subtypes/animal/passive/mouse.dm
Labels: Needs Discussion

#8067 [Deck 1/2/3] SC Maints+
  maps/southern_cross/southern_cross-1.dmm
  maps/southern_cross/southern_cross-2.dmm
  maps/southern_cross/southern_cross-3.dmm
Labels: Needs Discussion, Map Edit

#8077 Borg access
  code/game/machinery/air_alarm.dm
  code/game/machinery/portable_turret.dm
  code/modules/power/apc.dm
  modular_chomp/code/modules/mob/living/silicon/robot/robot.dm
Labels: TEST MERGED, TEST MERGE CANDIDATE

#8147 TG overlay subsystem
  code/__defines/overlay_ch.dm
  code/controllers/subsystems/overlays.dm
  code/controllers/subsystems/overlays_ch.dm
  code/game/machinery/atmoalter/canister.dm
  code/game/machinery/cell_charger.dm
  code/game/machinery/floodlight.dm
  code/game/machinery/spaceheater.dm
  code/game/objects/items/devices/defib.dm
  code/game/objects/items/devices/paicard.dm
  code/game/objects/structures/reflectors_ch.dm
  code/game/turfs/simulated/dungeon/wall.dm
  code/modules/assembly/holder.dm
  code/modules/food/food/z_custom_food_vr.dm
  code/modules/food/kitchen/gibber.dm
  code/modules/hydroponics/beekeeping/beehive.dm
  code/modules/multiz/turf.dm
  code/modules/paperwork/adminpaper.dm
  code/modules/paperwork/clipboard.dm
  code/modules/paperwork/folders.dm
  code/modules/paperwork/paper.dm
  code/modules/paperwork/paperplane.dm
  code/modules/pda/ai.dm
  code/modules/pda/pda.dm
  code/modules/pda/pda_subtypes.dm
  code/modules/pda/pda_vr.dm
  code/modules/persistence/noticeboard.dm
  code/modules/persistence/noticeboard_yw.dm
  code/modules/power/cell.dm
  code/modules/power/cells/power_cells.dm
  code/modules/shieldgen/energy_shield.dm
  icons/Testing/greyscale_error.dmi
  maps/southern_cross/southern_cross-6.dmm
  modular_chomp/code/game/objects/items/devices/flipper.dm
  modular_chomp/code/modules/mob/living/carbon/human/species/station/protean/protean_rig.dm
  modular_chomp/code/modules/power/cells/power_cells.dm
  vorestation.dme
Labels: TEST MERGED, TEST MERGE CANDIDATE

#8146 Maintenance Deck
  code/modules/power/gravitygenerator_vr.dm
  code/modules/projectiles/projectile/beams.dm
  maps/southern_cross/overmap/sectors.dm
  maps/southern_cross/southern_cross-0.dmm
  maps/southern_cross/southern_cross-1.dmm
  maps/southern_cross/southern_cross-2.dmm
  maps/southern_cross/southern_cross-3.dmm
  maps/southern_cross/southern_cross.dm
  maps/southern_cross/southern_cross_areas.dm
  maps/southern_cross/southern_cross_defines.dm
  maps/southern_cross/southern_cross_elevator.dm
  maps/southern_cross/southern_cross_presets.dm
  modular_chomp/code/game/objects/mob_spawner.dm
Labels: Map Edit, TEST MERGED, TEST MERGE CANDIDATE

#8175 fuck you cache
  code/modules/organs/organ_icon.dm
  modular_chomp/code/modules/organs/organ_icon.dm
Labels: TEST MERGED, TEST MERGE CANDIDATE

#8157 ports more hair overrides
  modular_chomp/code/modules/mob/new_player/sprite_accessories.dm
  modular_chomp/icons/mob/hair_skrell.dmi
  modular_chomp/icons/mob/hair_skrell_add.dmi
  modular_chomp/icons/mob/hair_unathi.dmi
  modular_chomp/icons/mob/hair_unathi_add.dmi
Labels: TEST MERGED, TEST MERGE CANDIDATE

#8220 scrollingFixes
  tgui/packages/tgui-panel/chat/renderer.jsx
  tgui/packages/tgui/components/Autofocus.tsx
  tgui/packages/tgui/components/Section.tsx
  tgui/packages/tgui/components/Tabs.tsx
  tgui/packages/tgui/events.ts
  tgui/packages/tgui/interfaces/BodyDesigner.jsx
  tgui/packages/tgui/interfaces/chompstation/TicketsPanel.tsx
  tgui/packages/tgui/interfaces/chompstation/VorePanel/VoreBellySelectionAndCustomization.jsx
  tgui/packages/tgui/interfaces/chompstation/VorePanel/index.tsx
  tgui/packages/tgui/layouts/Layout.tsx
Labels: TEST MERGED, Type: UI, TEST MERGE CANDIDATE

#8261 Icon access violation crash prevention attempt
  code/modules/clothing/clothing.dm
  code/modules/clothing/clothing_icons.dm
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: TEST MERGED

#8166 Completely refactor planetary lighting
  code/__defines/lighting_ch.dm
  code/controllers/subsystems/lighting.dm
  code/controllers/subsystems/planets.dm
  code/game/turfs/simulated_ch.dm
  code/game/turfs/turf_changing.dm
  code/modules/lighting/lighting_corner.dm
  code/modules/lighting/lighting_overlay.dm
  code/modules/lighting/lighting_source.dm
  code/modules/lighting/lighting_turf.dm
  code/modules/lighting/planet_sunlight_ch.dm
  code/modules/lighting/sunlight_handler_ch.dm
  code/modules/planet/sif.dm
  code/modules/planet/sun.dm
  code/modules/planet/thor.dm
  vorestation.dme
Labels: TEST MERGED, TEST MERGE CANDIDATE

#8274 Another cached icon edit
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: TEST MERGED

#8296 Remove many incorrect uses of usr
  code/game/machinery/camera/tracking.dm
  code/game/objects/items/devices/communicator/communicator.dm
  code/game/objects/items/devices/spy_bug.dm
  code/modules/client/preference_setup/general/01_basic.dm
  code/modules/client/preference_setup/general/02_language.dm
  code/modules/client/preference_setup/general/03_body.dm
  code/modules/client/preference_setup/general/04_equipment.dm
  code/modules/client/preference_setup/general/05_background.dm
  code/modules/client/preference_setup/general/06_flavor.dm
  code/modules/client/preference_setup/occupation/occupation.dm
  code/modules/client/preference_setup/volume_sliders/01_volume.dm
  code/modules/client/preference_setup/volume_sliders/02_media.dm
  code/modules/client/preference_setup/vore/02_size.dm
  code/modules/client/preference_setup/vore/07_traits.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_vr.dm
  code/modules/mob/living/login.dm
  code/modules/power/cable.dm
  code/modules/vore/eating/living_vr.dm
  code/modules/vore/eating/vorepanel_vr.dm
  modular_chomp/code/modules/mob/living/living.dm
Labels: TEST MERGE CANDIDATE

#8307 8d10 psychic damage (lighting memory optimizations)
  code/modules/lighting/sunlight_handler_ch.dm
Labels: TEST MERGED, TEST MERGE CANDIDATE

#8207 Kinetic Things and Weird Goggle
  modular_chomp/code/modules/clothing/glasses/glasses.dm
  modular_chomp/code/modules/mining/tools.dm
  modular_chomp/icons/inventory/eyes/glasses.dmi
  modular_chomp/icons/inventory/eyes/mob.dmi
Labels: Needs Discussion

#8277 [MIRROR] some borg upgrade overhaul, power use function, bluespace pounce and some fixes
  code/__defines/misc.dm
  code/__defines/mobs.dm
  code/__defines/span_vr.dm
  code/game/objects/items/robot/robot_items.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/mob/living/silicon/robot/dogborg/dog_modules_vr.dm
  code/modules/mob/living/silicon/robot/inventory.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_damage.dm
  code/modules/mob/mob.dm
  code/modules/projectiles/guns/launcher/confetti.dm
  code/modules/research/prosfab_designs.dm
  code/modules/vore/eating/belly_obj_ch.dm
  icons/mob/dogborg_vr.dmi
  modular_chomp/code/modules/mob/living/silicon/robot/dogborg/dog_modules.dm
Labels: Needs Discussion
