Repository CHOMPStation2/CHOMPStation2, pull requests merged in 2024-01, with the labels that each got.

#7448 Borgmultibelly
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/sprites/_sprite_datum.dm
  code/modules/mob/living/silicon/robot/sprites/civilian.dm
  code/modules/vore/eating/vorepanel_vr.dm
  modular_chomp/code/modules/mob/living/silicon/robot/robot.dm
  modular_chomp/code/modules/mob/living/silicon/robot/sprites/_sprite_datum.dm
  tgui/packages/tgui_ch/interfaces/VorePanel.jsx
  tgui/public/tgui.bundle.js
  tools/build/build.js
  vorestation.dme
Labels: TEST MERGED

#7539 Lost and Found Remap v2
  maps/southern_cross/southern_cross-1.dmm
  maps/southern_cross/southern_cross-2.dmm
  maps/southern_cross/southern_cross-3.dmm
Labels: Map Edit

#7518 Indirect VoreFX
  code/modules/mob/living/carbon/human/life.dm
  code/modules/vore/eating/belly_obj_ch.dm
  code/modules/vore/eating/belly_obj_vr.dm
  code/modules/vore/eating/bellymodes_vr.dm
  code/modules/vore/eating/living_ch.dm
  code/modules/vore/eating/vorepanel_vr.dm
  modular_chomp/code/game/objects/items/weapons/capture_crystal.dm
Labels: TEST MERGED

#7435 [MIRROR] Custom indexeddb store
  interface/skin.dmf
  tgui/packages/tgui-panel/themes.js
  tgui/public/tgui-panel.bundle.js
Labels: [MIRROR] Missing files

#7465 [WIP] New shadekin ability
  code/modules/mob/living/carbon/human/species/shadekin/shadekin.dm
  code/modules/mob/living/carbon/human/species/shadekin/shadekin_abilities.dm
  code/modules/mob/living/simple_mob/subtypes/vore/shadekin/ability_objects.dm
  code/modules/mob/living/simple_mob/subtypes/vore/shadekin/ability_procs.dm
  code/modules/mob/living/simple_mob/subtypes/vore/shadekin/shadekin.dm
  icons/mob/screen_spells.dmi
  modular_chomp/code/game/objects/effects/dark_growth.dm
  modular_chomp/icons/obj/Shadekin_powers_2.dmi
  modular_chomp/icons/obj/shadekin_portal.dmi
Labels: TEST MERGED

#7633 [MIRROR] Raptor sprite overhaul
  code/modules/mob/living/silicon/robot/sprites/combat.dm
  code/modules/mob/living/silicon/robot/sprites/event.dm
  code/modules/mob/living/silicon/robot/sprites/science.dm
  code/modules/mob/living/silicon/robot/sprites/security.dm
  code/modules/mob/living/silicon/robot/sprites/syndicate.dm
  code/modules/projectiles/projectile/energy.dm
  icons/mob/robot/combat_large.dmi
  icons/mob/robot/crisis_large.dmi
  icons/mob/robot/engineering_large.dmi
  icons/mob/robot/gravekeeper_large.dmi
  icons/mob/robot/janitor_large.dmi
  icons/mob/robot/lost_large.dmi
  icons/mob/robot/mining_large.dmi
  icons/mob/robot/science_large.dmi
  icons/mob/robot/security_large.dmi
  icons/mob/robot/service_large.dmi
  icons/mob/robot/surgical_large.dmi
  icons/mob/robot/syndie_large.dmi
  sound/weapons/Laser4.ogg
Labels: Mirror Needs Manual Implementation
