Repository CHOMPStation2/CHOMPStation2, pull requests merged in 2024-07, with the labels that each got.

#8644 Extra Auto-Transfer Locations
  code/modules/vore/eating/belly_obj_vr.dm
  code/modules/vore/eating/vorepanel_vr.dm
  modular_chomp/code/modules/vore/eating/exportpanel_ch.dm
  tgui/packages/tgui/interfaces/chompstation/VorePanel/VoreSelectedBellyInteractions.tsx
  tgui/packages/tgui/interfaces/chompstation/VorePanel/types.ts
  tgui/packages/tgui/interfaces/chompstation/VorePanelExport/VorePanelExportBellyString.tsx
  tgui/packages/tgui/interfaces/chompstation/VorePanelExport/VorePanelExportBellyStringHelpers.tsx
  tgui/packages/tgui/interfaces/chompstation/VorePanelExport/constants.ts
  tgui/packages/tgui/interfaces/chompstation/VorePanelExport/types.ts
Labels: JavaScript / TypeScript

#8650 Removes round start sci PA, Moves ore storage to cargo warehouse.
  maps/southern_cross/southern_cross-2.dmm
  maps/southern_cross/southern_cross-3.dmm
Labels: Needs Discussion

#8643 Changes loci to address some issues
  code/modules/artifice/telecube.dm
Labels: Needs Discussion

#8557 [MIRROR] New event species - Part 1
  code/__defines/chemistry_vr.dm
  code/__defines/mobs_vr.dm
  code/__defines/species_languages_vr.dm
  code/game/objects/structures/props/rocks.dm
  code/game/turfs/simulated/water.dm
  code/modules/clothing/spacesuits/void/ert_vr.dm
  code/modules/mob/language/station_vr.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_species_vr.dm
  code/modules/mob/living/carbon/human/species/lleill/lleill.dm
  code/modules/mob/living/carbon/human/species/lleill/lleill_abilities.dm
  code/modules/mob/living/carbon/human/species/lleill/lleill_items.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/simple_mob/subtypes/glamour/homunculus.dm
  code/modules/mob/new_player/sprite_accessories_ear_vr.dm
  code/modules/mob/new_player/sprite_accessories_tail.dm
  code/modules/mob/new_player/sprite_accessories_tail_vr.dm
  code/modules/mob/new_player/sprite_accessories_vr.dm
  code/modules/mob/new_player/sprite_accessories_wing_vr.dm
  code/modules/multiz/portals_vr.dm
  code/modules/organs/subtypes/lleill.dm
  icons/mob/human_face_vr.dmi
  icons/mob/human_races/r_lleill.dmi
  icons/mob/species/lleill/tail.dmi
  icons/mob/vore.dmi
  icons/mob/vore/ears_32x64.dmi
  icons/obj/glamour.dmi
  icons/turf/flooring/glamour.dmi
  vorestation.dme
Labels: Needs Review
