Repository CHOMPStation2/CHOMPStation2, pull requests merged in 2024-05, with the labels that each got.

#8333 List killening
  code/game/objects/structures.dm
  code/game/turfs/flooring/seasonal.dm
  code/game/turfs/simulated/floor_types_eris.dm
  code/game/turfs/simulated/outdoors/dirt.dm
  code/game/turfs/simulated/outdoors/grass.dm
  code/game/turfs/simulated/outdoors/grass_ch.dm
  code/game/turfs/simulated/outdoors/outdoors.dm
  code/game/turfs/simulated/outdoors/outdoors_ch.dm
  code/game/turfs/simulated/outdoors/snow.dm
  code/game/turfs/simulated/wall_types.dm
  code/modules/mob/living/simple_mob/subtypes/animal/alien animals/stardog.dm
  maps/southern_cross/overmap/planets/thor/thor.dm
  maps/southern_cross/turfs/outdoors.dm
  modular_chomp/code/game/turfs/simulated/outdoors/desert_planet.dm
  modular_chomp/code/game/turfs/simulated/outdoors/lava_land.dm
  modular_chomp/code/game/turfs/simulated/outdoors/valley.dm
  modular_chomp/code/game/turfs/turf.dm
  modular_chomp/code/modules/planet/smokestar/turf.dm
  vorestation.dme
Labels: TEST MERGED, TEST MERGE CANDIDATE

#8347 [MIRROR] Adds new buildmode - DROP
  code/modules/admin/verbs/buildmode.dm
  icons/misc/buildmode.dmi
Labels: Type: Feature / Enhancement

#8348 [MIRROR] Adds drop vore to mob falling objects
  code/game/objects/items/falling_object_vr.dm
Labels: Type: Feature / Enhancement

#8345 Fixes borg hand interactions with force-buckled mobs
  code/modules/mob/living/silicon/robot/robot_vr.dm
Labels: Fix

#8353 Various map fixes
  maps/southern_cross/overmap/planets/thor/thor.dmm
  maps/southern_cross/submaps/gateway/darkrps.dm
  maps/southern_cross/submaps/gateway/darkrps.dmm
  modular_chomp/code/modules/mining/shelters_ch.dm
  modular_chomp/maps/overmap/space_pois/space_pois.dm
  modular_chomp/maps/overmap/space_pois/spacebar_40x40.dmm
  modular_chomp/maps/overmap/space_pois/ussp_84x90.dmm
  modular_chomp/maps/submaps/shelters/CultShip-28x17.dmm
  modular_chomp/maps/submaps/shelters/MechFabShip-27x24.dmm
Labels: Map Edit
