Repository CHOMPStation2/CHOMPStation2, pull requests merged in 2024-03, with the labels that each got.

#7837 Updates dreaming code
  code/__defines/traits.dm
  code/_global_vars/traits.dm
  code/game/objects/structures/bedsheet_bin.dm
  modular_chomp/code/_HELPERS/type2type.dm
  modular_chomp/code/_global_vars/list/names.dm
  modular_chomp/code/modules/flufftext/Dreaming.dm
  modular_chomp/strings/dreamstrings.txt
  modular_chomp/strings/names/adjectives.txt
  modular_chomp/strings/names/adverbs.txt
  modular_chomp/strings/names/ing_verbs.txt
  modular_chomp/strings/names/verbs.txt
  vorestation.dme
Labels: Type: Feature / Enhancement, TEST MERGED

#7855 Various backend fixes/tweaks
  code/ATMOSPHERICS/datum_pipe_network.dm
  code/ATMOSPHERICS/pipes/simple.dm
  code/__defines/machinery.dm
  code/_helpers/sorts/TimSort.dm
  code/_helpers/sorts/__main.dm
  code/controllers/subsystems/garbage.dm
  code/controllers/subsystems/machines.dm
  code/datums/datum.dm
  code/datums/reference_tracking.dm
  code/game/machinery/machinery.dm
  code/game/world.dm
  code/global.dm
  code/modules/DMAPI/st_commands.dm
  code/modules/DMAPI/st_interface.dm
  code/modules/DMAPI/yawnDMAPI.dm
  code/modules/admin/verbs/atmosdebug.dm
  code/modules/admin/verbs/grief_fixers.dm
Labels: TEST MERGED

#7822 Crawling
  code/game/machinery/portable_turret.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_movement.dm
  code/modules/vore/eating/living_ch.dm
Labels: Type: Feature / Enhancement, TEST MERGED

#7851 Timer subsystem update
  code/__defines/_helpers.dm
  code/__defines/_lists.dm
  code/__defines/assert.dm
  code/__defines/math.dm
  code/__defines/subsystems.dm
  code/_helpers/_lists.dm
  code/controllers/subsystems/timer.dm
  code/datums/datum.dm
  vorestation.dme
Labels: Type: Feature / Enhancement, TEST MERGED

#7873 Various runtimes
  code/datums/chat_message.dm
  code/game/machinery/cryopod.dm
  code/game/objects/items/devices/text_to_speech.dm
  code/modules/client/client procs.dm
  code/modules/client/preference_setup/general/03_body.dm
  code/modules/mob/living/simple_mob/subtypes/vore/bigdragon.dm
  code/modules/mob/mob.dm
  code/modules/reagents/reagents/dispenser.dm
  code/modules/tgui/tgui.dm
  code/modules/vore/eating/belly_obj_vr.dm
Labels: TEST MERGED

#7844 [READY TO MERGE] Public Sheet Storage, Timeclock Changes
  code/game/machinery/computer/timeclock_vr.dm
  maps/southern_cross/southern_cross-2.dmm
Labels: TEST MERGED

#7889 Reversions and fixes
  code/_helpers/global_lists.dm
  code/_helpers/mobs.dm
  code/_helpers/sorts/TimSort.dm
  code/_helpers/sorts/__main.dm
  code/_onclick/hud/ability_screen_objects.dm
  code/_onclick/hud/minihud_rigmech.dm
  code/controllers/globals.dm
  code/controllers/subsystems/ping.dm
  code/core/image/Transform.dm
  code/datums/chat_message.dm
  code/datums/observation/moved.dm
  code/datums/progressbar.dm
  code/game/machinery/computer/camera.dm
  code/game/machinery/portable_turret.dm
  code/game/mecha/equipment/tools/shield_omni.dm
  code/game/objects/effects/overlays.dm
  code/game/objects/items/devices/gps.dm
  code/game/objects/items/stacks/stack.dm
  code/game/turfs/simulated.dm
  code/modules/client/preference_setup/loadout/loadout_shoes_vr.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/broodmother_spawn.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/mecha/mecha.dm
  code/modules/mob/mob.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/power/singularity/particle_accelerator/particle.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/projectile.dm
  code/modules/reagents/holder/holder.dm
  code/modules/reagents/reagents/dispenser.dm
  code/modules/recycling/disposal.dm
  code/modules/shieldgen/directional_shield.dm
  code/modules/vore/chat_healthbars.dm
  code/modules/vore/eating/belly_obj_vr.dm
  code/modules/vore/eating/bellymodes_vr.dm
Labels: TEST MERGED

#7915 Bumps 515 version to stable one
  .tgs.yml
  _build_dependencies.sh
Labels: Infrastructure

#7917 More runtimes
  code/_helpers/unsorted.dm
  code/modules/mob/living/bot/farmbot.dm
  code/modules/projectiles/targeting/targeting_overlay.dm
  modular_chomp/code/modules/mob/living/simple_mob/subtypes/humanoid/eclipse/eclipse.dm
Labels: TEST MERGED, Fix

#7903 Small Engineering QoL Improvement
  maps/southern_cross/southern_cross-2.dmm
  maps/southern_cross/southern_cross-7.dmm
Labels: Quality of Life

#7887 Deprecates BYOND 514
  code/__byond_version_compat.dm
  code/game/socket_talk.dm
  code/game/world.dm
  code/modules/ext_scripts/irc.dm
  code/modules/webhooks/_webhook.dm
Labels: Infrastructure

#7926 fix vorepanel icon duplication
  tgui/packages/tgui/interfaces/chompstation/VorePanel/VoreBellySelectionAndCustomization.jsx
  tgui/packages/tgui/interfaces/chompstation/VorePanel/VoreContentsPanel.tsx
Labels: Type: UI, Fix

#7939 Viper Suit Spritefix
  icons/mob/taursuits_naga_alt_ch.dmi
Labels: Icon Edit, Fix

#7934 Some little MC & Subsystem updates
  code/controllers/master.dm
  code/controllers/subsystem.dm
  code/datums/helper_datums/stack_end_detector_ch.dm
  vorestation.dme
Labels: Quality of Life

#7938 Properly defines a few global vars
  code/controllers/failsafe.dm
  code/game/birthday.dm
  code/game/jobs/whitelist.dm
  code/game/jobs/whitelist_vr.dm
  code/game/objects/effects/landmarks.dm
  code/game/turfs/flooring/seasonal.dm
  code/game/turfs/simulated/floor_icon.dm
  code/modules/client/preference_setup/loadout/loadout.dm
  code/modules/events/roaming_wildlife.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/simple_mob/subtypes/animal/squirrel.dm
  code/modules/mob/login_ch.dm
  code/modules/mob/mob.dm
  modular_chomp/code/game/objects/effects/step_triggers.dm
  modular_chomp/code/global.dm
  modular_chomp/code/modules/admin/verbs/randomverbs.dm
  modular_chomp/code/modules/client/preference_setup/loadout/gear_tweaks.dm
  modular_chomp/code/modules/client/preferences_spawnpoints.dm
  modular_chomp/code/modules/event/meatyores.dm
  modular_chomp/code/modules/flufftext/Dreaming.dm
  modular_chomp/code/modules/recycling/v_garbosystem.dm
Labels: Quality of Life

#7944 Changed some verbs to tgui input
  code/modules/admin/admin_tools.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/admin/verbs/resize.dm
Labels: Type: UI, Quality of Life

#7877 Balloon Alerts
  code/game/objects/items/mail_ch.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/stacks/nanopaste.dm
  code/game/objects/items/trash_vr.dm
  code/modules/economy/coins.dm
  code/modules/events/brand_intelligence.dm
  code/modules/food/food/snacks.dm
  code/modules/mining/drilling/drill.dm
  code/modules/mob/autowhisper.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/taste.dm
  code/modules/reagents/reagent_containers/_reagent_containers.dm
  code/modules/reagents/reagent_containers/borghypo.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/reagents/reagent_containers/pill.dm
  code/modules/reagents/reagent_containers/spray.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/reagents/reagent_containers/syringes_vr.dm
  code/modules/surgery/bones.dm
  code/modules/surgery/encased.dm
  code/modules/surgery/external_repair.dm
  code/modules/surgery/face.dm
  code/modules/surgery/generic.dm
  code/modules/surgery/implant.dm
  code/modules/surgery/limb_reattach.dm
  code/modules/surgery/neck.dm
  code/modules/surgery/organ_ripper_vr.dm
  code/modules/surgery/organs_internal.dm
  code/modules/surgery/other.dm
  code/modules/surgery/robotics.dm
  code/modules/surgery/surgery.dm
  code/modules/telesci/bscyrstal.dm
  code/modules/vore/eating/living_vr.dm
  modular_chomp/code/_HELPERS/game.dm
  modular_chomp/code/__defines/_planes+layers.dm
  modular_chomp/code/__defines/text.dm
  modular_chomp/code/game/atoms/atoms.dm
  modular_chomp/code/modules/balloon_alert/balloon_alert.dm
  vorestation.dme
Labels: TEST MERGED, TEST MERGE CANDIDATE

#7979 Deck 1 rewiring
  maps/southern_cross/southern_cross-1.dmm
Labels: Map Edit

#7958 the smoothening
  code/controllers/configuration.dm
  code/modules/mob/mob_movement.dm
  code/world.dm
  modular_chomp/code/modules/mob/mob.dm
Labels: TEST MERGED, TEST MERGE CANDIDATE

#7992 Remove recursivemove + signals from being on EVERY machine by default
  code/game/machinery/machinery_power.dm
Labels: TEST MERGED, TEST MERGE CANDIDATE

#7940 Turfpacks system for mappers
  modular_chomp/code/game/turfs/turfpacks/packs_sim/turfpacks_sim_outdoors.dm
  modular_chomp/code/game/turfs/turfpacks/packs_sim/turfpacks_sim_special.dm
  modular_chomp/code/game/turfs/turfpacks/packs_sim/turfpacks_sim_tiled.dm
  modular_chomp/code/game/turfs/turfpacks/packs_sim/turfpacks_sim_walls.dm
  modular_chomp/code/game/turfs/turfpacks/packs_unsim/turfpacks_unsim_outdoors.dm
  modular_chomp/code/game/turfs/turfpacks/packs_unsim/turfpacks_unsim_special.dm
  modular_chomp/code/game/turfs/turfpacks/packs_unsim/turfpacks_unsim_tiled.dm
  modular_chomp/code/game/turfs/turfpacks/packs_unsim/turfpacks_unsim_walls.dm
  modular_chomp/code/game/turfs/turfpacks/turfpacks.dm
  modular_chomp/code/game/turfs/turfpacks/unsim_turfs/unsim_turfs.dm
  modular_chomp/code/game/turfs/turfpacks/unsim_turfs/unsim_turfs_outdoors.dm
  modular_chomp/code/game/turfs/turfpacks/unsim_turfs/unsim_turfs_special.dm
  modular_chomp/code/game/turfs/turfpacks/unsim_turfs/unsim_turfs_tiles.dm
  modular_chomp/code/game/turfs/turfpacks/unsim_turfs/unsim_turfs_walls.dm
  vorestation.dme
Labels: Type: Feature / Enhancement

#7950 Updated server admin announcements
  code/modules/admin/admin.dm
  modular_chomp/code/_HELPERS/announcements.dm
  modular_chomp/code/__defines/span.dm
  modular_chomp/sound/misc/bloop.ogg
  tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss
  tgui/packages/tgui-panel/styles/tgchat/chat-light.scss
  tgui/packages/tgui-panel/styles/tgchat/chat-vchatdark.scss
  tgui/packages/tgui-panel/styles/tgchat/chat-vchatlight.scss
  vorestation.dme
Labels: Type: UI, Quality of Life

#7937 Several harddels/runtimes
  code/game/gamemodes/technomancer/spells/spawner/pulsar.dm
  code/modules/entopics_vr/alternate_appearance.dm
  code/modules/mob/freelook/ai/eye.dm
  code/modules/mob/living/simple_mob/life.dm
  code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/broodmother_spawn.dm
  code/modules/mob/mob.dm
Labels: TEST MERGED, TEST MERGE CANDIDATE

#8064 Orbit refactor
  code/modules/mob/dead/observer/observer.dm
  code/modules/power/tesla/energy_ball.dm
  modular_chomp/code/datums/components/orbiter.dm
  vorestation.dme
Labels: TEST MERGED

#8059 TGPanel Patch 1
  code/__defines/statpanel_ch.dm
  code/_helpers/icons.dm
  code/controllers/subsystems/statpanel_ch.dm
  code/modules/asset_cache/assets/tgfont.dm
  code/modules/mob/living/simple_mob/subtypes/vore/bigdragon.dm
  code/modules/mob/living/simple_mob/subtypes/vore/shadekin/shadekin.dm
  modular_chomp/code/modules/mob/living/carbon/human/species/station/protean/protean_species.dm
  vorestation.dme
Labels: TEST MERGED, TEST MERGE CANDIDATE

#8086 Different chat icon tag method
  code/_helpers/text.dm
Labels: TEST MERGED

#7948 Properly defines a few global vars
  code/controllers/failsafe.dm
  code/game/birthday.dm
  code/game/jobs/whitelist.dm
  code/game/jobs/whitelist_vr.dm
  code/game/objects/effects/landmarks.dm
  code/game/turfs/flooring/seasonal.dm
  code/game/turfs/simulated/floor_icon.dm
  code/modules/client/preference_setup/loadout/loadout.dm
  code/modules/events/roaming_wildlife.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/simple_mob/subtypes/animal/squirrel.dm
  code/modules/mob/login_ch.dm
  code/modules/mob/mob.dm
  modular_chomp/code/game/objects/effects/step_triggers.dm
  modular_chomp/code/global.dm
  modular_chomp/code/modules/admin/verbs/randomverbs.dm
  modular_chomp/code/modules/client/preference_setup/loadout/gear_tweaks.dm
  modular_chomp/code/modules/client/preferences_spawnpoints.dm
  modular_chomp/code/modules/event/meatyores.dm
  modular_chomp/code/modules/flufftext/Dreaming.dm
  modular_chomp/code/modules/recycling/v_garbosystem.dm
Labels: TEST MERGED, Needs Manual Testing, TEST MERGE CANDIDATE

#8091 Replaces a section in space in VR into a Roleplay Mall
  maps/southern_cross/submaps/virtual_reality/constructVR.dm
  maps/southern_cross/submaps/virtual_reality/constructVR.dmm
  modular_chomp/game/objects/effects/step_triggers.dm
  sound/ambience/fluorescentlight.ogg
  vorestation.dme
Labels: Map Edit

#8090 custom egg size
  code/modules/vore/eating/belly_obj_vr.dm
  code/modules/vore/eating/bellymodes_datum_vr.dm
  code/modules/vore/eating/vorepanel_vr.dm
  modular_chomp/code/modules/vore/eating/exportpanel_ch.dm
  tgui/packages/tgui/interfaces/chompstation/VorePanel/VoreSelectedBellyOptions.tsx
Labels: Type: Feature / Enhancement

#7881 Subsystem return update
  code/__defines/dcs/signals_ch/signals_subsystem.dm
  code/__defines/span_vr.dm
  code/__defines/subsystems.dm
  code/controllers/master.dm
  code/controllers/subsystem.dm
  code/controllers/subsystems/air.dm
  code/controllers/subsystems/alarm.dm
  code/controllers/subsystems/atoms.dm
  code/controllers/subsystems/character_setup.dm
  code/controllers/subsystems/chemistry.dm
  code/controllers/subsystems/circuits.dm
  code/controllers/subsystems/dbcore.dm
  code/controllers/subsystems/events.dm
  code/controllers/subsystems/game_master.dm
  code/controllers/subsystems/holomaps.dm
  code/controllers/subsystems/input.dm
  code/controllers/subsystems/job.dm
  code/controllers/subsystems/lighting.dm
  code/controllers/subsystems/machines.dm
  code/controllers/subsystems/mail_ch.dm
  code/controllers/subsystems/mapping.dm
  code/controllers/subsystems/media_tracks.dm
  code/controllers/subsystems/nightshift.dm
  code/controllers/subsystems/overlays.dm
  code/controllers/subsystems/overmap_renamer_vr.dm
  code/controllers/subsystems/persistence.dm
  code/controllers/subsystems/planets.dm
  code/controllers/subsystems/plants.dm
  code/controllers/subsystems/player_tips.dm
  code/controllers/subsystems/processing/fastprocess.dm
  code/controllers/subsystems/processing/instruments.dm
  code/controllers/subsystems/processing/turfs.dm
  code/controllers/subsystems/reflect_ch.dm
  code/controllers/subsystems/robot_sprites.dm
  code/controllers/subsystems/shuttles.dm
  code/controllers/subsystems/skybox.dm
  code/controllers/subsystems/sounds.dm
  code/controllers/subsystems/sqlite.dm
  code/controllers/subsystems/sun.dm
  code/controllers/subsystems/supply.dm
  code/controllers/subsystems/ticker.dm
  code/controllers/subsystems/transcore_vr.dm
  code/controllers/subsystems/vis_overlays.dm
  code/controllers/subsystems/webhooks.dm
  code/controllers/subsystems/xenoarch.dm
  vorestation.dme
Labels: Type: Feature / Enhancement, TEST MERGED, TEST MERGE CANDIDATE

#8097 Time tweak again
  code/_helpers/time.dm
  code/game/world.dm
Labels: TEST MERGED

#8098 Statpanel + holder runtimes
  code/controllers/subsystems/statpanel_ch.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/mob/holder.dm
Labels: TEST MERGED

#8111 Fixes the verb manager based stat entries to show
  code/controllers/subsystems/verb_manager_ch.dm
Labels: Fix

#8023 Ai update
  code/__defines/_flags/turf_flags_ch.dm
  code/__defines/dcs/signals_ch.dm
  code/_helpers/distance_ch.dm
  code/_helpers/game.dm
  code/_helpers/graphs/astar_ch.dm
  code/_helpers/legacy_tg_path_ch.dm
  code/_helpers/pathfinding_ch/astar.dm
  code/_helpers/pathfinding_ch/common.dm
  code/_helpers/pathfinding_ch/jps.dm
  code/_helpers/priority_queue_ch.dm
  code/_onclick/adjacent.dm
  code/controllers/subsystems/pathfinder_ch.dm
  code/game/atoms.dm
  code/game/atoms_movable_ch.dm
  code/game/gamemodes/changeling/changeling_powers.dm
  code/game/machinery/doors/airlock_ch.dm
  code/game/machinery/doors/firedoor_ch.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/objects/items/weapons/id cards/station_ids.dm
  code/game/objects/objs.dm
  code/game/objects/structures/plasticflaps.dm
  code/game/objects/structures/window.dm
  code/game/turfs/turf.dm
  code/modules/ai/ai_holder_follow.dm
  code/modules/ai/ai_holder_movement.dm
  code/modules/ai/ai_holder_pathfinding.dm
  code/modules/ai/ai_holder_targeting.dm
  code/modules/integrated_electronics/subtypes/smart.dm
  code/modules/mob/living/bot/bot.dm
  code/modules/mob/living/bot/farmbot.dm
  code/modules/mob/living/simple_mob/subtypes/humanoid/mercs/mercs.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_movement_ch.dm
  code/modules/multiz/turf.dm
  code/modules/vore/eating/belly_obj_ch.dm
  icons/screen/debug/pathfinding.dmi
  modular_chomp/code/modules/client/hearable.dm
  tools/build/build-testing.ps1
  vorestation.dme
Labels: TEST MERGED, TEST MERGE CANDIDATE
