Repository CHOMPStation2/CHOMPStation2, pull requests merged in 2024-02, with the labels that each got.

#7567 vorepanel setting update
  code/game/jobs/job_controller.dm
  code/modules/admin/verbs/randomverbs_vr.dm
  code/modules/mob/living/carbon/human/species/shadekin/shadekin_abilities.dm
  code/modules/mob/living/simple_mob/subtypes/vore/vore.dm
  code/modules/reagents/reagents/dispenser.dm
  code/modules/reagents/reagents/vore_ch.dm
  code/modules/vore/eating/belly_obj_ch.dm
  code/modules/vore/eating/belly_obj_vr.dm
  code/modules/vore/eating/bellymodes_datum_vr.dm
  code/modules/vore/eating/bellymodes_vr.dm
  code/modules/vore/eating/living_ch.dm
  code/modules/vore/eating/living_vr.dm
  code/modules/vore/eating/mob_ch.dm
  code/modules/vore/eating/mob_vr.dm
  code/modules/vore/eating/vore_vr.dm
  code/modules/vore/eating/vorepanel_vr.dm
  code/modules/vore/mouseray.dm
  modular_chomp/code/modules/mob/living/simple_mob/simple_mob.dm
  tgui/packages/tgui_ch/interfaces/VorePanel.jsx
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.js
Labels: TEST MERGED

#7419 Adding some sprites I've had sitting around unfinished
  code/modules/mob/login_ch.dm
  icons/mob/vore/taurs_ch.dmi
  modular_chomp/code/modules/admin/verbs/randomverbs.dm
  modular_chomp/code/modules/mob/living/carbon/human/species/station/protean/protean_blob.dm
  modular_chomp/code/modules/mob/living/carbon/human/species/station/protean/protean_powers.dm
  modular_chomp/code/modules/mob/living/carbon/human/species/station/protean/protean_rig.dm
  modular_chomp/code/modules/mob/living/carbon/human/species/station/protean/protean_species.dm
  modular_chomp/code/modules/mob/new_player/sprite_accessories_taur.dm
  modular_chomp/code/modules/mob/new_player/sprite_accessories_wing.dm
  modular_chomp/icons/mob/human_races/sprite_accessories/wings64.dmi
  modular_chomp/icons/mob/species/protean/protean.dmi
  modular_chomp/icons/mob/species/protean/protean128x64.dmi
  modular_chomp/icons/mob/species/protean/protean64x32.dmi
  modular_chomp/icons/mob/species/protean/protean64x64.dmi
  vorestation.dme
Labels: WIP, TEST MERGED

#7742 Overmap POI mapping overhauls
  maps/southern_cross/southern_cross-7.dmm
  modular_chomp/maps/overmap/space_pois/abandonedzoo_20x20.dmm
  modular_chomp/maps/overmap/space_pois/abandonedzoo_50x50.dmm
  modular_chomp/maps/overmap/space_pois/asteroid1_20x20.dmm
  modular_chomp/maps/overmap/space_pois/asteroid1_60x60.dmm
  modular_chomp/maps/overmap/space_pois/asteroid2_20x20.dmm
  modular_chomp/maps/overmap/space_pois/asteroid2_60x60.dmm
  modular_chomp/maps/overmap/space_pois/asteroid3_20x20.dmm
  modular_chomp/maps/overmap/space_pois/asteroid3_60x60.dmm
  modular_chomp/maps/overmap/space_pois/asteroid4_20x20.dmm
  modular_chomp/maps/overmap/space_pois/asteroid4_60x60.dmm
  modular_chomp/maps/overmap/space_pois/asteroid5_40x40.dmm
  modular_chomp/maps/overmap/space_pois/blowntcommsat_53x56.dmm
  modular_chomp/maps/overmap/space_pois/debris1_20x20.dmm
  modular_chomp/maps/overmap/space_pois/debris1_60x60.dmm
  modular_chomp/maps/overmap/space_pois/deepstorage_85x67.dmm
  modular_chomp/maps/overmap/space_pois/derelict1_100x100.dmm
  modular_chomp/maps/overmap/space_pois/derelict1_40x40.dmm
  modular_chomp/maps/overmap/space_pois/dj_31x28.dmm
  modular_chomp/maps/overmap/space_pois/druglab_16x14.dmm
  modular_chomp/maps/overmap/space_pois/druglab_32x32.dmm
  modular_chomp/maps/overmap/space_pois/intactemptyship_13x11.dmm
  modular_chomp/maps/overmap/space_pois/intactemptyship_30x25.dmm
  modular_chomp/maps/overmap/space_pois/oldstation_80x45.dmm
  modular_chomp/maps/overmap/space_pois/onehalf_60x20.dmm
  modular_chomp/maps/overmap/space_pois/space_areas.dm
  modular_chomp/maps/overmap/space_pois/space_pois.dm
  modular_chomp/maps/overmap/space_pois/spacebar_40x40.dmm
  modular_chomp/maps/overmap/space_pois/spaceseveneleven_45x45.dmm
  modular_chomp/maps/overmap/space_pois/syndiedepot_57x49.dmm
  modular_chomp/maps/overmap/space_pois/ussp_84x90.dmm
  modular_chomp/maps/overmap/space_pois/whiteship_55x30.dmm
Labels: Map Edit

#7789 No more bundle
  tgui/.gitattributes
  tgui/.gitignore
  tgui/bin/tgui_.ps1
  tgui/packages/tgfont/.gitignore
  tgui/packages/tgfont/dist/tgfont.css
  tgui/packages/tgfont/dist/tgfont.eot
  tgui/packages/tgfont/dist/tgfont.woff2
  tgui/packages/tgfont/icons/ATTRIBUTIONS.md
  tgui/packages/tgfont/icons/bad-touch.svg
  tgui/packages/tgfont/icons/prosthetic-full.svg
  tgui/packages/tgfont/icons/prosthetic-leg.svg
  tgui/packages/tgfont/icons/syndicate-logo.svg
  tgui/packages/tgfont/static/tgfont.css
  tgui/packages/tgfont/static/tgfont.eot
  tgui/packages/tgfont/static/tgfont.woff2
  tgui/public/tgui-panel.bundle.css
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.css
  tgui/public/tgui.bundle.js
  tools/ci/build_tgui.sh
  tools/ci/compile_and_run.sh
Labels: Type: UI

#7761 Attempting to please two crowds RE Shadekins and tcomms
  maps/southern_cross/southern_cross-1.dmm
Labels: Map Edit

#7805 Remove sky islands, retouch wilderness shelter for single Z courtesy of Bib
  maps/southern_cross/overmap/sectors.dm
  maps/southern_cross/southern_cross-10.dmm
  maps/southern_cross/southern_cross-5.dmm
  maps/southern_cross/southern_cross.dm
  maps/southern_cross/southern_cross_areas.dm
  maps/southern_cross/southern_cross_defines.dm
  maps/southern_cross/southern_cross_presets.dm
Labels: Map Edit

#7814 Little tgui update
  tgui/.eslintignore
  tgui/.eslintrc.yml
  tgui/packages/tgui-bench/entrypoint.tsx
  tgui/packages/tgui-bench/lib/benchmark.js
  tgui/packages/tgui-polyfill/1-misc.js
Labels: Type: UI

#7796 Ports TGS event handler
  code/__defines/span_vr.dm
  code/game/world.dm
  modular_chomp/datums/tgs_event_handler.dm
  vorestation.dme
Labels: Type: Feature / Enhancement, Type: Infrastructure

#7812 Breaking down the Vorepanel.jsx file
  tgui/packages/tgui/interfaces/chompstation/VorePanel.jsx
  tgui/packages/tgui/interfaces/chompstation/VorePanel/FeatureColorInput.tsx
  tgui/packages/tgui/interfaces/chompstation/VorePanel/LiquidColorInput.tsx
  tgui/packages/tgui/interfaces/chompstation/VorePanel/VoreBellySelectionAndCustomization.jsx
  tgui/packages/tgui/interfaces/chompstation/VorePanel/VoreContentsPanel.tsx
  tgui/packages/tgui/interfaces/chompstation/VorePanel/VoreInsidePanel.jsx
  tgui/packages/tgui/interfaces/chompstation/VorePanel/VoreSelectedBelly.tsx
  tgui/packages/tgui/interfaces/chompstation/VorePanel/VoreSelectedBellyControls.tsx
  tgui/packages/tgui/interfaces/chompstation/VorePanel/VoreSelectedBellyDescriptions.tsx
  tgui/packages/tgui/interfaces/chompstation/VorePanel/VoreSelectedBellyInteractions.tsx
  tgui/packages/tgui/interfaces/chompstation/VorePanel/VoreSelectedBellyLiquidMessages.tsx
  tgui/packages/tgui/interfaces/chompstation/VorePanel/VoreSelectedBellyLiquidOptions.tsx
  tgui/packages/tgui/interfaces/chompstation/VorePanel/VoreSelectedBellyOptions.tsx
  tgui/packages/tgui/interfaces/chompstation/VorePanel/VoreSelectedBellySounds.tsx
  tgui/packages/tgui/interfaces/chompstation/VorePanel/VoreSelectedBellyVisuals.tsx
  tgui/packages/tgui/interfaces/chompstation/VorePanel/VoreSelectedMobTypeBellyButtons.tsx
  tgui/packages/tgui/interfaces/chompstation/VorePanel/VoreUserPreferenceItem.tsx
  tgui/packages/tgui/interfaces/chompstation/VorePanel/VoreUserPreferences.jsx
  tgui/packages/tgui/interfaces/chompstation/VorePanel/constants.ts
  tgui/packages/tgui/interfaces/chompstation/VorePanel/index.tsx
Labels: Type: UI

#7835 [MIRROR] Smart Storage Tweaks
  code/modules/persistence/storage/smartfridge.dm
  code/modules/persistence/storage/storage.dm
Labels: Type: Feature / Enhancement, TEST MERGED
